export const GET_ALL_TASKS = 'GET_ALL_TASKS'
export const GET_ALL_TAGS = 'GET_ALL_TAGS'
export const TOGGLE_SELECTED_TAG = 'TOGGLE_SELECTED_TAG'
export const ENTER_CURRENT_TASK = 'ENTER_CURRENT_TASK'

